### ISSUE TITLE
Cannot give receiver port as cmd line argument

### ISSUE THREAD

**Issue by evanmjaffe** [okomestudio/socket_log_receiver#2]
python3 -m socket_log_receiver --receiver-host localhost --receiver-port 9020

Running above gives error that the port is a string, and socket cannot be opened (requires int).  Casting port to int solves the problem for me:
 
Receivers.py
 84     #receiver = Receiver(con["host"], con["port"])
 85     receiver = Receiver(con["host"], int(con["port"]))

**Comment by okomestudio** [comment]
Thank you very much for reporting. A fix has been applied.
